import onetimepad		
from tkinter import *
from PIL import ImageTk
from PIL import Image	
root = Tk()
root.title("CRYPTOGRAPHY")
root.geometry("620x200")
img =Image.open('C:\\Users\\Acer\\Desktop\\progarming-py\\cw1\\enc.jpg')
img=img.resize((620,200))
bg = ImageTk.PhotoImage(img)
label = Label(root, image=bg)
label.place(x =0,y =0)
def encryptMessage():					
	pt = e1.get()
	ct = onetimepad.encrypt(pt, 'RSA')
	e2.insert(0, ct)

def decryptMessage():					
	ct1 = e3.get()
	pt1 = onetimepad.decrypt(ct1, 'RSA')
	e4.insert(0, pt1)
	
label = Label(root, text="TRY TEXT ENCRYPTION AND DECRYPTION",foreground='maroon',bg='sky blue',font=("Arial", 12, "bold"))
label.grid(row=0, column=2)
label1 = Label(root, text ='Plane text',font=("Arial", 10, "bold"))			
label1.grid(row = 11, column = 1)
label2 = Label(root, text ='Encrypted code',font=("Arial", 10, "bold"))
label2.grid(row = 17, column = 1)
l3 = Label(root, text ="Encrypted code",font=("Arial", 10, "bold"))
l3.grid(row = 11, column = 3)
l4 = Label(root, text ="Decrypted text",font=("Arial", 10, "bold"))
l4.grid(row = 17, column = 3)
e1 = Entry(root,bg='light green',bd=5)
e1.grid(row = 13, column = 1)
e2 = Entry(root,bg='light green',bd=5)
e2.grid(row = 18, column = 1)
e3 = Entry(root,bg='light green',bd=5)
e3.grid(row = 13, column = 3)
e4 = Entry(root,bg='light green',bd=5)
e4.grid(row = 18, column = 3)
ent = Button(root, text = "Encrypt", bg ="red", fg ="white", command = encryptMessage,font=("Arial", 14, "bold"))
ent.grid(row = 16, column = 1)
b2 = Button(root, text = "Decrypt", bg ="orange", fg ="white", command = decryptMessage,font=("Arial", 14, "bold"))
b2.grid(row = 16, column = 3)
root.mainloop()
